apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  imagePullSecrets:
    - name: mydockerhubregistry
  containers:
  - name: k8s-demo
    image: jmajumde/nodejs-helloworld-v1    
    ports:
    - name: nodejs-port
      containerPort: 3000
  